name: sbert-embedding

services:
  sbert-embedding:
    container_name: sbert-embedding-cpu
    build:
      context: ./services/sbert-embedding
      dockerfile: Dockerfile.cpu
    # Define environment variables here to override Dockerfile defaults
    environment:
       - SBERT_MODEL_NAME=all-MiniLM-L6-v2
       - WORKERS=2 # Example: Override worker count
    ports:
      - "8000:8000" # Map host port 8000 to container port 8000
    volumes:
      # Mount a volume to persist the model cache on the host
      - sbert_cache:/app/.cache
    restart: unless-stopped

volumes:
  sbert_cache:
